routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {

  Route::get('index_admin.html', 'PecahTemplateAdminController@index');
  Route::resource('admin_user', 'AdminUserController');


  //MANAJEMEN USER ===================================================================================================================================

  //  ================================================ GROUP ==========================================================
  Route::resource('group', 'GroupController');
  Route::get('data_group', 'GroupController@listData')->name('data_group');
  //  ================================================ END GROUP ==========================================================

  //  ================================================ MASTER USER ==========================================================
  Route::resource('master_user', 'MasterUserController');
  Route::get('data_master_user', 'MasterUserController@listData')->name('data_master_user');
  //  ================================================ END MASTER USER ==========================================================

  //  ================================================ MENU ==========================================================
  Route::resource('menu', 'MenuController');
  Route::get('data_menu', 'MenuController@listData')->name('data_menu');
  //  ================================================ END MENU ==========================================================

  //  ================================================ T USER ==========================================================
  Route::resource('t_user', 'TUserController');
  //  ================================================ END T USER ==========================================================

  //  ================================================ PEMBELIAN ==========================================================
  Route::get('data_pembelian', 'PembelianController@listData')->name('data_pembelian');
  Route::post('update_total_pembelian', 'PembelianController@totalBarang')->name('total_pembelian');
  Route::resource('pembelian', 'PembelianController');
  //  ================================================ END PEMBELIAN ==========================================================

  //  ================================================ DETAIL PEMBELIAN ==========================================================
  Route::get('get_data_barang/{id}', 'DetailPembelianController@getDataBarang')->name('get_pembelian');
  Route::get('detail_data_pembelian', 'DetailPembelianController@listData')->name('detail_data_pembelian');
  Route::resource('detail_pembelian', 'DetailPembelianController');
  //  ================================================ END DETAIL PEMBELIAN ==========================================================

  //  ================================================ DETAIL PEMBELIAN2 ==========================================================
  Route::resource('detail_pembelian2', 'DetailPembelian2Controller');
  //  ================================================ END DETAIL PEMBELIAN ==========================================================

  //END MANAJEMEN USER ===================================================================================================================================




  //KAS ===================================================================================================================================

  //  ================================================ KATEGORI KAS ==========================================================
  Route::resource('kategori', 'KategoriController');
  Route::get('data_kategori', 'KategoriController@listData')->name('data_kategori');
  //  ================================================ END KATEGORI KAS ==========================================================

  //  ================================================ PEMASUKAN ==========================================================
  Route::get('pemasukan', 'PemasukanController@index')->name('pemasukan.index');
  Route::get('pemasukan_create', 'PemasukanController@create');
  Route::post('pemasukan_store', 'PemasukanController@store')->name('pemasukan.store');
  Route::get('pemasukan_edit/{id}', 'PemasukanController@edit');
  Route::post('pemasukan_update', 'PemasukanController@update')->name('pemasukan.update');
  Route::get('pemasukan_delete/{id}', 'PemasukanController@delete');

  //  ================================================ END PEMASUKAN ==========================================================

  //  ================================================ PENGELUARAN ==========================================================
  Route::get('pengeluaran', 'PengeluaranController@index')->name('pengeluaran.index');
  Route::get('pengeluaran_create', 'PengeluaranController@create');
  Route::post('pengeluaran_store', 'PengeluaranController@store')->name('pengeluaran.store');
  Route::get('pengeluaran_edit/{id}', 'PengeluaranController@edit');
  Route::post('pengeluaran_update', 'PengeluaranController@update')->name('pengeluaran.update');
  Route::get('pengeluaran_delete/{id}', 'PengeluaranController@delete');
  //  ================================================ END PENGELUARAN ==========================================================

  //  ================================================ LAPORAN KAS ==========================================================
  Route::get('laporan_perbulan', 'LaporanPerbulanController@index')->name('laporan_perbulan.index');
  Route::post('laporan_perbulan_cari', 'LaporanPerbulanController@cari')->name('laporan_perbulan_cari.cari');
  Route::get('laporan_perbulan_pdf/{bulan}/{tahun}', 'LaporanPerbulanController@laporanPerBulanPdf');
  //  ================================================ END LAPORAN KAS ==========================================================

  //END KAS ===================================================================================================================================


// adhajdahj


  //jhj


});

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use Redirect;
use App\MenuModel;

class MenuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $menu = MenuModel::where('menu_id_parent','=','0')->get();
      return view('admin.menu.index', compact('menu'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $menu = new MenuModel;
      $menu ->menu_id_parent = $request['menu_id_parent'];
      $menu ->menu_nama = $request['menu_nama'];
      $menu ->menu_link = $request['menu_link'];
      $menu -> save();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $menu = MenuModel::find($id);
      echo json_encode($menu);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $menu = MenuModel::find($id);
      $menu ->menu_id_parent = $request['menu_id_parent'];
      $menu ->menu_nama = $request['menu_nama'];
      $menu ->menu_link = $request['menu_link'];
      $menu -> update();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $menu = MenuModel::find($id);
      $menu -> delete();
    }

    public function listData()
    {
        $menu = MenuModel::orderBy('menu_id', 'DESC')->get();
        $no = 0;
        $data = array();
        foreach ($menu as $list) {

          $menu_id = $list->menu_id_parent;
          if ($menu_id!=0) {
            $nama_menu = MenuModel::where('menu_id', '=', $menu_id)->value('menu_nama');
          }else {
            $nama_menu = "--";
          }


            $no++;
            $row = array();
            $row[] = $no;
            $row[] = $list->menu_nama;
            $row[] = $list->menu_link;
            $row[] = $nama_menu;
            $row[] = '<a onclick="editForm('.$list->menu_id.')" class="btn btn-primary" data-toggle="tooltip" data-placement="botttom" title="Edit Data"  style="color:white;"><i class="fa  fa-edit"></i></a>
            <a onclick="deleteData('.$list->menu_id.')" class="btn btn-danger" data-toggle="tooltip" data-placement="botttom" title="Hapus Data" style="color:white;"><i class="fa  fa-trash"></i></a>';
            $data[] = $row;

        }

        $output = array("data" => $data);
        return response()->json($output);

    }

}

resources/views/admin/menu/form.blade.php
<div class="modal" id="modal-form" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
  <div class="modal-dialog">


    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span></button>
          <h4 class="modal-title">Default Modal</h4>
        </div>
        <form class="form-horizontal" data-toggle="validator" method="post">
          {{ csrf_field() }} {{ method_field('POST') }}
          <div class="modal-body">
            <input type="hidden" id="id" name="id">


              <div class="form-group">
                <label class="col-sm-2 control-label">Parent</label>

                <div class="input-group col-sm-8">
                  <!-- <span class="input-group-addon"><i class="fa  fa-user"></i></span> -->
                  <select  id="menu_id_parent" name="menu_id_parent" class="form-control js-example-basic-single" style="width: 100%;">
                    <option value="0" >--</option>
                    @foreach($menu as $list)
                      <option  value="{{ $list->menu_id }}"> {{ $list->menu_nama }}</option>
                    @endforeach
                  </select>
                </div>
              </div>
              <!-- /.form-group -->

              <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">Nama Menu</label>

                <div class="input-group col-sm-8">
                  <!-- <span class="input-group-addon"><i class="fa  fa-user"></i></span> -->
                  <input type="text" class="form-control" required name="menu_nama" id="menu_nama" placeholder="Nama Menu" >
                  <span class="help-block with-errors"></span>
                </div>
              </div>
              <!-- /.form-group -->


            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 control-label">Link</label>

              <div class="input-group col-sm-8">
                <!-- <span class="input-group-addon"><i class="fa  fa-user"></i></span> -->
                <input type="text" class="form-control" required name="menu_link" id="menu_link" placeholder="Nama Link" >
                <span class="help-block with-errors"></span>
              </div>
            </div>
            <!-- /.form-group -->



          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-warning pull-left" data-dismiss="modal"><i class="fa fa-arrow-circle-left"></i> Batal</button>
            <button type="submit" class="btn btn-primary btn-save"><i class="fa fa-floppy-o"></i> Simpan </button>
          </div>
        </div>

      </form>

      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div>

resources/views/admin/menu/index.blade.php
<?php $hal = "menu"; ?>
@extends('layouts.admin.master')
@section('title', 'Master Barang')

@section('css')
<!-- DataTables -->
<link rel="stylesheet" href="{{asset('public/admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('public/admin/bower_components/select2/dist/css/select2.min.css')}}">

<style>
    .example-modal .modal {
      position: relative;
      top: auto;
      bottom: auto;
      right: auto;
      left: auto;
      display: block;
      z-index: 1;
    }

    .example-modal .modal {
      background: transparent !important;
    }
  </style>

@endsection


@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Master Barang
    <!-- <small>Data barang</small> -->
  </h1>
</section>
<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-xs-12">

      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Data Master Produk</h3>
        </div>
        <a onclick="addForm()"  style="margin-bottom:20px;margin-left:10px;" class="card-body-title"><button class="btn btn-primary"><i class="fa  fa-plus-square-o"></i> Tambah</button></a>
        <!-- /.box-header -->
        <div class="box-body">
          <table id="datatable1" class="table table-bordered table-striped">
            <thead>
              <tr>
                <th style="width:10%">No #</th>
                <th style="width:16%">Nama Menu</th>
                <th style="width:16%">Link</th>
                <th style="width:16%">Parent</th>
                <th style="width:10%">Action</th>
              </tr>
            </thead>
            <tbody>
            </tbody>
          </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</section>
<!-- /.content -->
@include('admin.menu.form')
@endsection


@section('js')
<!-- DataTables -->
<script src="{{asset('public/admin/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('public/admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<script src="{{asset('public/admin/bower_components/select2/dist/js/select2.full.min.js')}}"></script>

<script type="text/javascript">
var table, save_method;
$(function(){
  table = $('.table').DataTable({
    "processing" : true,
    "ajax" : {
      "url" : "{{ route('data_menu') }}",
      "type" : "GET"
    }
  });
  $('#modal-form form').validator().on('submit', function(e){
    if(!e.isDefaultPrevented()){
      var id = $('#id').val();
      if(save_method == "add") url = "{{ route('menu.store') }}";
      else url = "menu/"+id;
      $.ajax({
        url : url,
        type : "POST",
        data : $('#modal-form form').serialize(),
        success : function(data){
          $('#modal-form').modal('hide');
          table.ajax.reload();
          location.reload();
        },
        error : function(){
          alert("Tidak dapat menyimpan data!");
        }
      });
      return false;
    }
  });
});
function addForm(){
  save_method = "add";
  $('input[name=_method]').val('POST');
  $('#modal-form').modal('show');
  $('#modal-form form')[0].reset();
  $('.modal-title').text('Tambah Data Menu');
}
function editForm(id){
  save_method = "edit";
  $('input[name=_method]').val('PATCH');
  $('#modal-form form')[0].reset();
  $.ajax({
    url : "menu/"+id+"/edit",
    type : "GET",
    dataType : "JSON",
    success : function(data){
      $('#modal-form').modal('show');
      $('.modal-title').text('Edit Data Menu');
      $('#id').val(data.menu_id);
      $('#menu_nama').val(data.menu_nama);
      $('#menu_link').val(data.menu_link);
      $('#menu_id_parent').val(data.menu_id_parent).trigger('change');
    },
    error : function(){
      alert("Tidak dapat menampilkan data !!!");
    }
  });
}
function deleteData(id){
  if(confirm("Apakah yakin data akan dihapus?")){
    $.ajax({
      url : "menu/"+id,
      type : "POST",
      data : {'_method' : 'DELETE', '_token' : $('meta[name=csrf-token]').attr('content')},
      success : function(data){
        table.ajax.reload();
         location.reload();
      },
      error : function(){
        alert("Tidak dapat menghapus data!");
      }
    });
  }
}
</script>

<script>
$(function () {
  $('#example1').DataTable()
  $('#example2').DataTable({
    'paging'      : true,
    'lengthChange': false,
    'searching'   : false,
    'ordering'    : true,
    'info'        : true,
    'autoWidth'   : false
  })
})
</script>


<script>
  // $(function () {
  //   //Initialize Select2 Elements
  //   $('.select2').select2()
  // })
  $(document).ready(function() {
  $('.js-example-basic-single').select2({
    dropdownParent: $(".modal")
  });
});
</script>


@endsection