routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {

  Route::get('index_admin.html', 'PecahTemplateAdminController@index');
  Route::resource('admin_user', 'AdminUserController');


  //MANAJEMEN USER ===================================================================================================================================

  //  ================================================ GROUP ==========================================================
  Route::resource('group', 'GroupController');
  Route::get('data_group', 'GroupController@listData')->name('data_group');
  //  ================================================ END GROUP ==========================================================

  //  ================================================ MASTER USER ==========================================================
  Route::resource('master_user', 'MasterUserController');
  Route::get('data_master_user', 'MasterUserController@listData')->name('data_master_user');
  //  ================================================ END MASTER USER ==========================================================

  //  ================================================ MENU ==========================================================
  Route::resource('menu', 'MenuController');
  Route::get('data_menu', 'MenuController@listData')->name('data_menu');
  //  ================================================ END MENU ==========================================================

  //  ================================================ T USER ==========================================================
  Route::resource('t_user', 'TUserController');
  //  ================================================ END T USER ==========================================================

  //  ================================================ PEMBELIAN ==========================================================
  Route::get('data_pembelian', 'PembelianController@listData')->name('data_pembelian');
  Route::post('update_total_pembelian', 'PembelianController@totalBarang')->name('total_pembelian');
  Route::resource('pembelian', 'PembelianController');
  //  ================================================ END PEMBELIAN ==========================================================

  //  ================================================ DETAIL PEMBELIAN ==========================================================
  Route::get('get_data_barang/{id}', 'DetailPembelianController@getDataBarang')->name('get_pembelian');
  Route::get('detail_data_pembelian', 'DetailPembelianController@listData')->name('detail_data_pembelian');
  Route::resource('detail_pembelian', 'DetailPembelianController');
  //  ================================================ END DETAIL PEMBELIAN ==========================================================

  //  ================================================ DETAIL PEMBELIAN2 ==========================================================
  Route::resource('detail_pembelian2', 'DetailPembelian2Controller');
  //  ================================================ END DETAIL PEMBELIAN ==========================================================

  //END MANAJEMEN USER ===================================================================================================================================




  //KAS ===================================================================================================================================

  //  ================================================ KATEGORI KAS ==========================================================
  Route::resource('kategori', 'KategoriController');
  Route::get('data_kategori', 'KategoriController@listData')->name('data_kategori');
  //  ================================================ END KATEGORI KAS ==========================================================

  //  ================================================ PEMASUKAN ==========================================================
  Route::get('pemasukan', 'PemasukanController@index')->name('pemasukan.index');
  Route::get('pemasukan_create', 'PemasukanController@create');
  Route::post('pemasukan_store', 'PemasukanController@store')->name('pemasukan.store');
  Route::get('pemasukan_edit/{id}', 'PemasukanController@edit');
  Route::post('pemasukan_update', 'PemasukanController@update')->name('pemasukan.update');
  Route::get('pemasukan_delete/{id}', 'PemasukanController@delete');

  //  ================================================ END PEMASUKAN ==========================================================

  //  ================================================ PENGELUARAN ==========================================================
  Route::get('pengeluaran', 'PengeluaranController@index')->name('pengeluaran.index');
  Route::get('pengeluaran_create', 'PengeluaranController@create');
  Route::post('pengeluaran_store', 'PengeluaranController@store')->name('pengeluaran.store');
  Route::get('pengeluaran_edit/{id}', 'PengeluaranController@edit');
  Route::post('pengeluaran_update', 'PengeluaranController@update')->name('pengeluaran.update');
  Route::get('pengeluaran_delete/{id}', 'PengeluaranController@delete');
  //  ================================================ END PENGELUARAN ==========================================================

  //  ================================================ LAPORAN KAS ==========================================================
  Route::get('laporan_perbulan', 'LaporanPerbulanController@index')->name('laporan_perbulan.index');
  Route::post('laporan_perbulan_cari', 'LaporanPerbulanController@cari')->name('laporan_perbulan_cari.cari');
  Route::get('laporan_perbulan_pdf/{bulan}/{tahun}', 'LaporanPerbulanController@laporanPerBulanPdf');
  //  ================================================ END LAPORAN KAS ==========================================================

  //END KAS ===================================================================================================================================


// adhajdahj


  //jhj


});

app/Http/Controllers/TUserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use Redirect;
use App\GroupModel;
use App\TUserModel;
use App\MenuModel;

class TUserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $t_user = new TUserModel;
        $group_id = $request['group_id'];

        DB::table('tbl_t_user')->where('group_id', '=', $group_id)->delete();

        if(!empty($request['menu_id'])) {
        foreach($request['menu_id'] as $menu_id){
            // echo "value : ".$menu_id.'<br/>';
            DB::table('tbl_t_user')->insert(array('group_id' => $group_id, 'menu_id' => $menu_id));

        }
        return Redirect::route('t_user.show',$group_id)->with('error',1);
      }else {
        return Redirect::route('t_user.show',$group_id)->with('error',1);
      }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $menu = MenuModel::orderBy('menu_id_parent','ASC')->get();
        $nama_group = GroupModel::where('group_id','=',$id)->value('group_nama');
        $t_user = TUserModel::join('tbl_menu','tbl_menu.menu_id','=','tbl_t_user.menu_id')->where('tbl_t_user.group_id','=',$id)->get();

        $menu2 = MenuModel::where('menu_id_parent','=','0')->get();

        return view('admin.t_user.menu', compact('menu', 'nama_group','id','t_user','menu2'))->with('error',0);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $group_id = TUserModel::where('t_user_id','=',$id)->value('group_id');
        $t_user = TUserModel::find($id);
        $t_user->delete();
        return Redirect::route('t_user.show',$group_id);
        // dd($group_id);
    }
}

resources/views/admin/t_user/menu.blade.php
<?php $hal = "group";
use App\TUserModel;?>
@extends('layouts.admin.master')
@section('title', 'Manajemen User - Menu Group')

@section('css')
<!-- DataTables -->
<link rel="stylesheet" href="{{asset('public/admin/bower_components/select2/dist/css/select2.min.css')}}">
<link rel="stylesheet" href="{{asset('public/admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">

<style>
.example-modal .modal {
  position: relative;
  top: auto;
  bottom: auto;
  right: auto;
  left: auto;
  display: block;
  z-index: 1;
}

.example-modal .modal {
  background: transparent !important;
}

hr.style3 {
	border-top: 1px dashed #8c8b8b;
}
</style>

@endsection


@section('content')
<!-- Content Header (Page header) -->



<section class="content-header">
  <h1>
    Menu Group
    <!-- <small>Data barang</small> -->
  </h1>
</section>
<!-- Main content -->
<section class="content">

    <div class="box box-default">
      <div class="box-header with-border">
        <h3 class="box-title">{{$nama_group}}</h3>

        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
          <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
        </div>
      </div>
      <!-- /.box-header -->
      <div class="box-body" style="">
        <?php if (session('error') == 1) {
          ?>
          <div class="alert alert-success" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            Success : <strong class="d-block d-sm-inline-block-force">Data berhasil dirubah !</strong>
          </div><!-- alert -->
          <?php
        } ?>


        <div class="row">
          <div class="col-md-12">


            <!-- form start -->
            <form class="form-horizontal" action="{{ route('t_user.store') }}" method="post">
              {{csrf_field()}}
              <input type="hidden" name="group_id" value="{{$id}}">
              <div class="box-header">
                <a href="{{route('group.index')}}" class="btn btn-warning pull-left"><i class="fa fa-arrow-circle-left"></i> Kembali</a>
                <button type="submit" class="btn btn-primary btn-save pull-right"><i class="fa fa-floppy-o"></i> Simpan </button>
              </div>
              <div class="box-body">
                <hr class="style3" style="margin:-3px">
                <!-- <?php  ?> -->
                <?php $count = 1; ?>
                @foreach($menu2 as $data)

                <?php $no=1; ?>

                <div class="form-group" >
                  <?php
                    if ($data->menu_id_parent!=0) {
                      $style = "margin-left: 15px;";
                    }else {
                      $style = "margin-left: 5px;";
                    }
                   ?>
                  <label for="inputPassword3" class="col-sm-6 control-label" style="text-align:left;"><div style="{{$style}}">
                    {{$count}}.&nbsp {{$data->menu_nama}}
                  </div></label>
                  <div class="col-sm-6">
                    <div class="checkbox">
                      <label>


                        <?php
                        $t_user_id = TUserModel::where([
                          ['menu_id', '=', $data->menu_id],
                          ['group_id', '=', $id],
                          ])->value('t_user_id');
                          // echo "string = ".$t_user_id;
                          $menu_id = TUserModel::where('t_user_id','=',$t_user_id)->value('menu_id');

                          ?>
                          <input type="checkbox" name='menu_id[]' value="{{$data->menu_id}}" <?php if(($data->menu_id==$menu_id)) { ?> checked="checked" <?php } ?> >



                        </label>
                      </div>
                    </div>
                  </div>
                  <hr class="style3" style="margin:-3px">

                @foreach(App\MenuModel::where('menu_id_parent', '=', $data->menu_id)->get() as $menuItem)

                <div class="form-group" >
                  <?php
                    if ($menuItem->menu_id_parent!=0) {
                      $style = "margin-left: 20px;";
                    }else {
                      $style = "margin-left: 5px;";
                    }
                   ?>
                  <label for="inputPassword3" class="col-sm-6 control-label" style="text-align:left;"><div style="{{$style}}">
                  {{$count}}.{{$no}}.&nbsp {{$menuItem->menu_nama}}
                  </div></label>
                  <div class="col-sm-6">
                    <div class="checkbox">
                      <label>


                        <?php
                        $t_user_id = TUserModel::where([
                          ['menu_id', '=', $menuItem->menu_id],
                          ['group_id', '=', $id],
                          ])->value('t_user_id');
                          // echo "string = ".$t_user_id;
                          $menu_id = TUserModel::where('t_user_id','=',$t_user_id)->value('menu_id');

                          ?>
                          <input type="checkbox" name='menu_id[]' value="{{$menuItem->menu_id}}" <?php if(($menuItem->menu_id==$menu_id)) { ?> checked="checked" <?php } ?> >



                        </label>
                      </div>
                    </div>
                  </div>
                  <hr class="style3" style="margin:-3px">
                  <?php $no++ ?>
                  @endforeach
                  <?php $count ++ ?>
                  @endforeach
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                  <a href="{{route('group.index')}}" class="btn btn-warning pull-left"><i class="fa fa-arrow-circle-left"></i> Kembali</a>
                  <button type="submit" class="btn btn-primary btn-save pull-right"><i class="fa fa-floppy-o"></i> Simpan </button>
                </div>
                <!-- /.box-footer -->
              </form>

              <!-- /.form-group -->
              <div class="form-group">
              </div>
              <!-- /.form-group -->
            </div>
            <!-- /.col -->

          </div>
          <!-- /.row -->
        </div>
        <!-- /.box-body -->
      </div>

  </section>
  <!-- /.content -->
  @endsection


  @section('js')
  <!-- DataTables -->
  <script src="{{asset('public/admin/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
  <script src="{{asset('public/admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
  <script src="{{asset('public/admin/bower_components/select2/dist/js/select2.full.min.js')}}"></script>


  <script>
  $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>




<script>
$(document).ready(function() {
  $('.js-example-basic-single').select2({
  });
});


$(".alert").delay(4000).slideUp(200, function() {
  $(this).alert('close');
});

</script>

@endsection

resources/views/admin/t_user/menu_lama.blade.php
<?php $hal = "group";
use App\TUserModel;?>
@extends('layouts.admin.master')
@section('title', 'Manajemen User - Menu Group')

@section('css')
<!-- DataTables -->
<link rel="stylesheet" href="{{asset('public/admin/bower_components/select2/dist/css/select2.min.css')}}">
<link rel="stylesheet" href="{{asset('public/admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">

<style>
.example-modal .modal {
  position: relative;
  top: auto;
  bottom: auto;
  right: auto;
  left: auto;
  display: block;
  z-index: 1;
}

.example-modal .modal {
  background: transparent !important;
}

hr.style3 {
	border-top: 1px dashed #8c8b8b;
}
</style>

@endsection


@section('content')
<!-- Content Header (Page header) -->



<section class="content-header">
  <h1>
    Menu Group
    <!-- <small>Data barang</small> -->
  </h1>
</section>
<!-- Main content -->
<section class="content">

  <div class="box box-default">
    <div class="box-header with-border">
      <h3 class="box-title">{{$nama_group}}</h3>

      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body" style="">
      <?php if (session('error') == 1) {
        ?>
        <div class="alert alert-success" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          Success : <strong class="d-block d-sm-inline-block-force">Data berhasil dirubah !</strong>
        </div><!-- alert -->
        <?php
      } ?>


      <div class="row">
        <div class="col-md-12">


          <!-- form start -->
          <form class="form-horizontal" action="{{ route('t_user.store') }}" method="post">
            {{csrf_field()}}
            <input type="hidden" name="group_id" value="{{$id}}">
            <div class="box-header">
              <a href="{{route('group.index')}}" class="btn btn-warning pull-left"><i class="fa fa-arrow-circle-left"></i> Kembali</a>
              <button type="submit" class="btn btn-primary btn-save pull-right"><i class="fa fa-floppy-o"></i> Simpan </button>
            </div>
            <div class="box-body">
              <hr class="style3" style="margin:-3px">
              <!-- <?php  ?> -->
              <?php $count = 0; ?>
              @foreach($menu as $data)
              <div class="form-group" >
                <?php
                  if ($data->menu_id_parent!=0) {
                    $style = "margin-left: 15px;";
                  }else {
                    $style="";
                  }
                 ?>
                <label for="inputPassword3" class="col-sm-6 control-label" style="text-align:left;"><div style="{{$style}}">
                  {{$data->menu_nama}}
                </div></label>
                <div class="col-sm-6">
                  <div class="checkbox">
                    <label>
                      <?php
                      $t_user_id = TUserModel::where([
                        ['menu_id', '=', $data->menu_id],
                        ['group_id', '=', $id],
                        ])->value('t_user_id');
                        // echo "string = ".$t_user_id;
                        $menu_id = TUserModel::where('t_user_id','=',$t_user_id)->value('menu_id');

                        ?>
                        <input type="checkbox" name='menu_id[]' value="{{$data->menu_id}}" <?php if(($data->menu_id==$menu_id)) { ?> checked="checked" <?php } ?> >
                      </label>
                    </div>
                  </div>
                </div>
                <hr class="style3" style="margin:-3px">
                @endforeach
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <a href="{{route('group.index')}}" class="btn btn-warning pull-left"><i class="fa fa-arrow-circle-left"></i> Kembali</a>
                <button type="submit" class="btn btn-primary btn-save pull-right"><i class="fa fa-floppy-o"></i> Simpan </button>
              </div>
              <!-- /.box-footer -->
            </form>

            <!-- /.form-group -->
            <div class="form-group">
            </div>
            <!-- /.form-group -->
          </div>
          <!-- /.col -->

        </div>
        <!-- /.row -->
      </div>
      <!-- /.box-body -->
    </div>


  </section>
  <!-- /.content -->
  @endsection


  @section('js')
  <!-- DataTables -->
  <script src="{{asset('public/admin/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
  <script src="{{asset('public/admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
  <script src="{{asset('public/admin/bower_components/select2/dist/js/select2.full.min.js')}}"></script>


  <script>
  $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>




<script>
$(document).ready(function() {
  $('.js-example-basic-single').select2({
  });
});


$(".alert").delay(4000).slideUp(200, function() {
  $(this).alert('close');
});

</script>

@endsection